name: Reddit Digest

on:
  workflow_dispatch:

jobs:
  reddit-digest:
    runs-on: ubuntu-latest

    # ← pull in your existing repo secrets as ENV for every step:
    env:
      OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
      OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
      REDDIT_CLIENT_ID:  ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_SECRET:     ${{ secrets.REDDIT_SECRET }}
      REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      REDDIT_USERNAME:   ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD:   ${{ secrets.REDDIT_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install praw requests pyyaml

      - name: Generate Reddit Digest
        run: python digest.py

      - name: List generated digests
        run: |
          echo "=== contents of digests/ ==="
          ls -l digests/

      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: reddit-digest
          path: digests/*.md

      - name: Commit & push digest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add digests/*.md
          git commit -m "chore: add Reddit Digest for $(date +'%Y-%m-%d')"
          git push
