name: Reddit Digest

# Trigger manually or on a daily schedule at 08:00 UTC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  reddit-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml praw requests

      - name: Generate Reddit Digest
        env:
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
          REDDIT_CLIENT_ID:  ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET:     ${{ secrets.REDDIT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          REDDIT_USERNAME:   ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD:   ${{ secrets.REDDIT_PASSWORD }}
        run: |
          python digest.py

      - name: List generated digests
        run: |
          echo "=== contents of digests/ ==="
          ls -R digests || echo "(no digests found)"

      - name: Upload digest artifact
        uses: actions/upload-artifact@v4
        with:
          name: reddit-digest
          path: digests/*.md

      - name: Commit & push digest
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if compgen -G "digests/*.md" > /dev/null; then
            git add digests/*.md
            if ! git diff --cached --quiet; then
              git commit -m "chore: update Reddit digest for $(date +'%Y-%m-%d')"
              git push
            else
              echo "▶️ No changes to digests/*.md, skipping commit"
            fi
          else
            echo "▶️ No digests/*.md files found, skipping commit"
          fi
