name: Reddit Digest

# trigger manually or on a schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # every day at 08:00 UTC (adjust as you like)

jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - uses: actions/checkout@v3

      # 2. Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install your deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml praw requests

      # 4. Run the digest script
      - name: Generate Reddit Digest
        env:
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
          REDDIT_CLIENT_ID:  ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET:     ${{ secrets.REDDIT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python digest.py

      # 5. (Optional) Commit & push the markdown output back to your repo
      - name: Commit digest
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add digests/*.md
          git commit -m "🔄 Auto-update Reddit digest for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
