name: Reddit Digest

# Trigger manually or on a daily schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # every day at 08:00 UTC (adjust or remove as needed)

jobs:
  reddit-digest:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml praw requests

      # 4. Run your Python digest script
      - name: Generate Reddit Digest
        env:
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
          REDDIT_CLIENT_ID:  ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET:     ${{ secrets.REDDIT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python digest.py

      # 5. Commit & push any new or updated digests/*.md files
      - name: Commit & push digest
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Only proceed if there are any digest files
          if compgen -G "digests/*.md" > /dev/null; then
            git add digests/*.md

            # Only commit if there are staged changes
            if ! git diff --cached --quiet; then
              git commit -m "chore: update Reddit digest for $(date +'%Y-%m-%d')"
              git push
            else
              echo "▶️ No changes in digests/*.md, skipping commit"
            fi
          else
            echo "▶️ No digests/*.md files found, skipping commit"
          fi
