name: Reddit Digest

# Run on manual dispatch and (optionally) every morning at 8 AM UTC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'   # adjust or remove if you don't need a schedule

jobs:
  reddit-digest:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml praw requests

      # 4. Run your digest script
      - name: Generate Reddit Digest
        env:
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
          REDDIT_CLIENT_ID:  ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_SECRET:     ${{ secrets.REDDIT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        run: |
          python digest.py

      # 5. (Optional) Commit & push the generated markdown
      - name: Commit & push digest
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add digests/*.md
          git diff --quiet || git commit -m "chore: update Reddit digest for $(date +'%Y-%m-%d')"
          git push
        # only if you actually want the markdown back in the repo
